### PR TITLE
Update: Table headers redesign

### PR DESCRIPTION
**Pull request by zewolfe**

### CODE REVIEW

**Comment by zewolfe** [comment]
In regards to the bonus points:
"a.)" -- Most of it is being done in another PR/Branch.
"b.)" -- All of it is being done in another PR/Branch.

**Comment by JasperTimm** [comment]
Thanks for the text changes.

So... why are those changes in another PR? I can't see a related issue where it would be in... is there a reason you didn't add them as commits here?

Also with the header adjustment - I guess keep in mind that we're working on the Moto G4 and Samsung Galaxy Tab Active. You should have test devices there to check them out on, I'm using emulators with the set screen sizes and resolutions (which is hopefully close enough). My Moto G4 is not so happy with the alignment.

**Comment by zewolfe** [comment]
https://jira.ehealthafrica.org/browse/EID-173
https://jira.ehealthafrica.org/browse/EID-174

And those aren't being worked on by me.
The real devices seem happy with the alignment. Can't test your case scenario on an emulator sadly.

**Comment by JasperTimm** [comment]
Ok then, I guess we'll handle the rest in the other PRs and I'll trust the alignment is fine on the real devices.

Fine to merge once the conflict is resolved.

**Pull request merged**
